### ISSUE TITLE
SecureRandom -> Random::Secure

### ISSUE THREAD

**Issue by expeditiousRubyist** [ysbaddaden/scrypt-crystal#4]
This shard currently does not support Crystal 0.24 and above, which broke backwards compatibility with SecureRandom. Instead, Random::Secure should be used. It's effectively the same thing, just a name change.

**Comment by ysbaddaden** [comment]
You're right! This is fixed in [v0.2.2](https://github.com/ysbaddaden/scrypt-crystal/releases/tag/v0.2.2)

**Comment by expeditiousRubyist** [comment]
Okay, cool. Hopefully we don't see any more breaking changes in the Crystal standard library any time soon. Thanks for the quick response!
