### ISSUE TITLE
[Question] Halved salt length?

### ISSUE THREAD

**Issue by SlayerShadow** [ysbaddaden/scrypt-crystal#8]
Is it correct to use a half of salt length?

What dimensions of the default value? If 8 "bytes" (or 32 bits) then maybe it should return value in range `"12345678abcdef01"` instead of `"abcdef01"`. Because right now it means only 4 bytes (or 16 bits).

* In [src/scrypt.cr#L6](https://github.com/ysbaddaden/scrypt-crystal/blob/d4e74ad0737f345774f3c511be50feeb83e49c96/src/scrypt.cr#L6) (defaults) the salt length described as `8`:

```crystal
module Scrypt
  DEFAULT_KEY_LEN = 32
  DEFAULT_SALT_SIZE = 8
  # ...
end
```

* In [src/engine.cr#L22](https://github.com/ysbaddaden/scrypt-crystal/blob/d4e74ad0737f345774f3c511be50feeb83e49c96/src/engine.cr#L22) it returns a hex string so for the default of `8` it returns just only 4 bytes (16 bits) (1 byte in hex means `00` upto `ff`):

```crystal
def self.generate_salt(salt_size = DEFAULT_SALT_SIZE)
  Random::Secure.hex(salt_size // 2)
end
```

---

Other thing.

* Please note: for production [one of SCrypt docs](https://cryptobook.nakov.com/mac-and-key-derivation/scrypt) recommends to use salt from 64 to 128 bits length (8-16 bytes). _(I don't find any proves in RFCs about that)_
* In [src/password.cr#L12](https://github.com/ysbaddaden/scrypt-crystal/blob/d4e74ad0737f345774f3c511be50feeb83e49c96/src/password.cr#L12) it clamps from 8 to 32 "halves of bytes" (4-16 bytes, 16-128 bits):

```crystal
salt = Engine.generate_salt(salt_size.clamp(8, 32))
```

Maybe there should be used larger alphabet for salt generation instead of hex or remove the halving to prevent parameter misunderstandings. :thinking:

**Comment by ysbaddaden** [comment]
You're right. It's indeed a number of bytes represented as a hexadecimal string, hence 16-64 a-f chars :facepalm:

The tests with a raw script hash even show that (the salt is `bb7cf92fe8429365`).

Would you mind to fill a PR to fix that issue?

**Comment by SlayerShadow** [comment]
Ok thanks I'll do it.
